apiVersion: v1
kind: Service
metadata:
  name: ms-data-aggregation
  labels:
    app: ms-data-aggregation
spec:
  type: ClusterIP
  ports:
  - port: 8085
    targetPort: 8085
    protocol: TCP
  selector:
    app: ms-data-aggregation