apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-cart
  labels:
    app: ms-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-cart
  template:
    metadata:
      labels:
        app: ms-cart
    spec:
      containers:
      - name: ms-cart
        image: proyecto-fullstack3-ms-cart:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
        env:
        - name: JAVA_OPTS
          value: "-Xmx256m -Xms128m"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 45
          periodSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8083
          initialDelaySeconds: 20
          periodSeconds: 5
          failureThreshold: 6