spring:
  application:
    name: ms-inventory

  mongodb:
    uri: mongodb://localhost:27017/inventory_bd

mongock:
  migration-scan-package:
    - com.grupocordillera.ms_inventory.migrations

server:
  port: 8082