server:
  port: 8083

spring:
  application:
    name: ms-cart

  mongodb:
    uri: mongodb://mongodb:27017/cart_bd

inventory:
  url: http://ms-inventory:8082

jwt:
  secret:
    key: "f9A2kL7pQzR4vX9mN3bH5jW8sT1yC6xD"
  expiration: 86400000

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

sentry:
  dsn: ${SENTRY_DSN}
  environment: dev
  traces-sample-rate: 1.0