apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../frontend/k8s
  - ../backend/bff/k8s
  - ../backend/ms-cart/k8s
  - ../backend/ms-inventory/k8s
  - ../backend/ms-login/k8s
  - ../backend/ms-order/k8s
  - ../backend/ms-reporting/k8s
  - ../backend/ms-data-aggregation/k8s
  - ../backend/ms-analytics/k8s
  - ../mongo/k8s