server:
  port: 8084

spring:
  application:
    name: ms-order

  mongodb:
    uri: mongodb://mongodb:27017/order_bd

cart:
  url: http://ms-cart:8083

inventory:
  url: http://ms-inventory:8082

jwt:
  secret:
    key: "f9A2kL7pQzR4vX9mN3bH5jW8sT1yC6xD"
  expiration: 86400000

mongock:
  migration-scan-package:
    - com.grupocordillera.ms_order.migrations

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

sentry:
  dsn: ${SENTRY_DSN}
  environment: dev
  traces-sample-rate: 1.0