apiVersion: v1
kind: Service
metadata:
  name: ms-analytics
  labels:
    app: ms-analytics
spec:
  type: ClusterIP
  ports:
  - port: 8086
    targetPort: 8086
    protocol: TCP
  selector:
    app: ms-analytics