spring:
  application:
    name: ms-bff

  cloud:
    openfeign:
      client:
        config:

          default:
            connectTimeout: 3000
            readTimeout: 5000

          ms-login:
            url: http://ms-login:8081

          ms-inventory:
            url: http://ms-inventory:8082

          ms-cart:
            url: http://ms-cart:8083

          ms-order:
            url: http://ms-order:8084

server:
  port: 8080