spring:
  application:
    name: ms-bff

  cloud:
    openfeign:
      client:
        config:

          default:
            connectTimeout: 3000
            readTimeout: 5000

          ms-login:
            url: http://ms-login:8081

          ms-inventory:
            url: http://ms-inventory:8082

          ms-cart:
            url: http://ms-cart:8083

          ms-order:
            url: http://ms-order:8084

          ms-reporting:
            url: http://ms-reporting:8087

server:
  port: 8080

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

sentry:
  dsn: ${SENTRY_DSN}
  environment: dev
  traces-sample-rate: 1.0